CREATE SEQUENCE reservation_id_seq START WITH 1000 INCREMENT BY 1;

CREATE TABLE reservation_events (
        id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        reservation_id   BIGINT       NOT NULL,
        reservation_code VARCHAR(255) NOT NULL,
        event_type       VARCHAR(50)  NOT NULL,
        data             TEXT         NOT NULL,
        occurred_at      TIMESTAMP    NOT NULL
);